### ISSUE TITLE
When I run python Helixer.py, met: "ImportError: cannot import name 'where' from 'certifi' (unknown location"

### ISSUE THREAD

**Issue by kuangzhuoran** [usadellab/Helixer#134]
I just installed Helixer like:
pip install -r requirements.3.10.txt
pip install .

Then I run "python Helixer.py -h", I met error: "ImportError: cannot import name 'where' from 'certifi' (unknown location"

(zhuoran) [kuangzhuoran@mu01 Helixer]$ python ./Helixer.py 
Traceback (most recent call last):
  File "/beegfs/home/kuangzhuoran/software/Helixer/./Helixer.py", line 13, in <module>
    from helixer.core.data import prioritized_models, report_if_current_not_best, identify_current, MODEL_PATH
  File "/beegfs/home/kuangzhuoran/software/Helixer/helixer/core/data.py", line 5, in <module>
    import requests
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/zhuoran/lib/python3.10/site-packages/requests/__init__.py", line 147, in <module>
    from . import packages, utils
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/zhuoran/lib/python3.10/site-packages/requests/utils.py", line 24, in <module>
    from . import certs
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/zhuoran/lib/python3.10/site-packages/requests/certs.py", line 14, in <module>
    from certifi import where
ImportError: cannot import name 'where' from 'certifi' (unknown location)

**Comment by alisandra** [comment]
Not sure on why this error is coming up, but using singularity (now named apptainer) is surely an easier way to install Helixer:

get apptainer installed: https://apptainer.org/docs/admin/main/installation.html

run like this (except replace 'singularity' with 'apptainer') https://github.com/gglyptodon/helixer-docker#running-via-singularity

**Comment by felicitas215** [comment]
I'm closing this issue, because there was no activity for one year. Feel free to reopen the issue if necessary.
